export const translations = {
    fa: {
      title: 'جستجوی تاریخچه مرورگر',
      keyword: 'کلیدواژه',
      matchType: 'نوع جستجو',
      contains: 'شامل',
      exact: 'دقیق',
      domain: 'دامنه',
      startTime: 'از تاریخ',
      endTime: 'تا تاریخ',
      minVisits: 'حداقل تعداد بازدید',
      search: 'جستجو',
      deleteSelected: 'حذف انتخاب شده‌ها',
      deleteAll: 'حذف همه موارد',
      exportCsv: 'خروجی CSV',
      exportJson: 'خروجی JSON',
      darkMode: 'حالت تاریک',
      noResults: 'نتیجه‌ای یافت نشد.',
      totalResults: 'تعداد کل نتایج',
      totalVisits: 'تعداد کل بازدیدها',
      resultsLabel: 'تعداد نتایج',
      visitsLabel: 'تعداد بازدیدها',
      example: 'مثال'
    },
    en: {
      title: 'Browser History Search',
      keyword: 'Keyword',
      matchType: 'Match Type',
      contains: 'Contains',
      exact: 'Exact',
      domain: 'Domain',
      startTime: 'From Date',
      endTime: 'To Date',
      minVisits: 'Minimum Visits',
      search: 'Search',
      deleteSelected: 'Delete Selected',
      deleteAll: 'Delete All',
      exportCsv: 'Export CSV',
      exportJson: 'Export JSON',
      darkMode: 'Dark Mode',
      noResults: 'No results found.',
      totalResults: 'Total Results',
      totalVisits: 'Total Visits',
      resultsLabel: 'Results Count',
      visitsLabel: 'Visits Count',
      example: 'Example'
    }
  };

  export const elements = {
    keywordInput: document.getElementById('keyword'),
    matchTypeSelect: document.getElementById('matchType'),
    domainInput: document.getElementById('domain'),
    startTimeInput: document.getElementById('startTime'),
    endTimeInput: document.getElementById('endTime'),
    minVisitsInput: document.getElementById('minVisits'),
    searchBtn: document.getElementById('searchBtn'),
    deleteSelectedBtn: document.getElementById('deleteSelectedBtn'),
    deleteAllBtn: document.getElementById('deleteAllBtn'),
    exportCsvBtn: document.getElementById('exportCsvBtn'),
    exportJsonBtn: document.getElementById('exportJsonBtn'),
    darkModeToggle: document.getElementById('darkModeToggle'),
    resultsDiv: document.getElementById('results'),
    statsDiv: document.getElementById('stats'),
    resultsBar: document.getElementById('resultsBar'),
    visitsBar: document.getElementById('visitsBar'),
    languageRadios: document.querySelectorAll('input[name="language"]'),
    heading: document.querySelector('h2'),
    darkModeLabel: document.querySelector('label[for="darkModeToggle"]'),
    resultsLabel: document.querySelector('#resultsBar .chart-label'),
    visitsLabel: document.querySelector('#visitsBar .chart-label'),
    labels: {
        keyword: document.querySelector('label[for="keyword"]'),
        matchType: document.querySelector('label[for="matchType"]'),
        domain: document.querySelector('label[for="domain"]'),
        startTime: document.querySelector('label[for="startTime"]'),
        endTime: document.querySelector('label[for="endTime"]'),
        minVisits: document.querySelector('label[for="minVisits"]')
    },
    selectOptions: {
        contains: document.querySelector('#matchType option[value="contains"]'),
        exact: document.querySelector('#matchType option[value="exact"]')
    }
  };
