export const translations = {
    fa: {
      persian: 'فارسی',
      english: 'English',
      title: 'جستجوی تاریخچه مرورگر',
      filters: 'فیلترها',
      keyword: 'کلیدواژه',
      matchType: 'نوع جستجو',
      contains: 'شامل',
      exact: 'دقیق',
      domain: 'دامنه',
      startTime: 'از تاریخ',
      endTime: 'تا تاریخ',
      minVisits: 'حداقل تعداد بازدید',
      search: 'جستجو',
      deleteSelected: 'حذف انتخاب شده‌ها',
      deleteAll: 'حذف همه موارد',
      exportCsv: 'خروجی CSV',
      exportJson: 'خروجی JSON',
      darkMode: 'حالت تاریک',
      noResults: 'نتیجه‌ای یافت نشد.',
      totalResults: 'تعداد کل نتایج',
      totalVisits: 'تعداد کل بازدیدها',
      resultsLabel: 'تعداد نتایج',
      visitsLabel: 'تعداد بازدیدها',
      example: 'مثال',
      searchPlaceholder: 'جستجو...',
      domainPlaceholder: 'مثال: google.com',
      minVisitsPlaceholder: '۱',
      noResults: 'نتیجه‌ای یافت نشد.',
      visits: 'بازدید',
      searchError: 'خطا در جستجو',
      url: 'نشانی'
    },
    en: {
      persian: 'Persian',
      english: 'English',
      title: 'Browser History Search',
      filters: 'Filters',
      keyword: 'Keyword',
      matchType: 'Match Type',
      contains: 'Contains',
      exact: 'Exact',
      domain: 'Domain',
      startTime: 'From Date',
      endTime: 'To Date',
      minVisits: 'Minimum Visits',
      search: 'Search',
      deleteSelected: 'Delete Selected',
      deleteAll: 'Delete All',
      exportCsv: 'Export CSV',
      exportJson: 'Export JSON',
      darkMode: 'Dark Mode',
      noResults: 'No results found.',
      totalResults: 'Total Results',
      totalVisits: 'Total Visits',
      resultsLabel: 'Results Count',
      visitsLabel: 'Visits Count',
      example: 'Example',
      searchPlaceholder: 'Search...',
      domainPlaceholder: 'e.g., google.com',
      minVisitsPlaceholder: '1',
      noResults: 'No results found.',
      visits: 'visits',
      searchError: 'Search error',
      url: 'URL'
    }
  };

  export function getElements() {
    return {
        searchBtn: document.getElementById('searchBtn'),
        resultsDiv: document.getElementById('results'),
        statsDiv: document.getElementById('stats'),
        keywordInput: document.getElementById('keyword'),
        matchTypeSelect: document.getElementById('matchType'),
        domainInput: document.getElementById('domain'),
        startTimeInput: document.getElementById('startTime'),
        endTimeInput: document.getElementById('endTime'),
        minVisitsInput: document.getElementById('minVisits'),
        deleteSelectedBtn: document.getElementById('deleteSelectedBtn'),
        deleteAllBtn: document.getElementById('deleteAllBtn'),
        exportCsvBtn: document.getElementById('exportCsvBtn'),
        exportJsonBtn: document.getElementById('exportJsonBtn'),
        darkModeToggle: document.getElementById('darkModeToggle'),
        darkModeLabel: document.querySelector('.dark-mode-toggle label'),
        heading: document.querySelector('.app-header h2'),
        translatableElements: Array.from(document.querySelectorAll('[data-i18n]')),
        translatableAttributes: Array.from(document.querySelectorAll('[data-i18n-placeholder], [data-i18n-aria-label]')),
        languageRadios: Array.from(document.querySelectorAll('input[name="language"]')),
        resultsBar: document.getElementById('resultsBar'),
        visitsBar: document.getElementById('visitsBar'),
        // سایر عناصر مورد نیاز...
    };
}
